HomeBundle\Entity\Contact:
    attributes:
        id:
            groups: ['user', 'contact', 'group', 'task']
        name:
            groups: ['user', 'contact', 'group', 'task']
        email:
            groups: ['user', 'contact', 'group', 'task']    
        user:
            groups: ['contact']
            
HomeBundle\Entity\Groupe:
    attributes:
        id:
            groups: ['user', 'contact', 'group', 'task']
        nom:
            groups: ['user', 'contact', 'group', 'task']
        description:
            groups: ['user', 'contact', 'group', 'task']    
        users:
            groups: ['group']
            
HomeBundle\Entity\Task:
    attributes:
        id:
            groups: ['user', 'contact', 'group', 'task']
        titre:
            groups: ['user', 'contact', 'group', 'task']
        localisation:
            groups: ['user', 'contact', 'group', 'task']
        isalarmeon:
            groups: ['user', 'contact', 'group', 'task']
        description:
            groups: ['user', 'contact', 'group', 'task']
        date:
            groups: ['user', 'contact', 'group', 'task']
        time:
            groups: ['user', 'contact', 'group', 'task']                    
        users:
            groups: ['task'] 
        manager:
            groups: ['task']      
        resp:
            groups: ['task'] 
        grroup:
            groups: ['task']                            