# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        auth_token_user_provider:
#            id: auth_token_user_provider
        fos_userbundle:
          id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:      ^/
#            anonymous:    true
#            stateless: true 
#            simple_preauth:
#                authenticator: auth_token_authenticator
            provider:     fos_user_provider
            anonymous: ~
            form_login:
                provider: fos_userbundle
                login_path: login
                use_forward: false
                check_path: login_check
                failure_path: null
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: false
                default_target_path:            /activite
            logout:
                path: /logout
                target: /
                invalidate_session: false
    encoders :
        SMARTASK\UserBundle\Entity\User: plaintext
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }