<?php

namespace SMARTASK\HomeBundle\Repository;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends \Doctrine\ORM\EntityRepository
{
	public function getRegisteredContactBuilder($userid)
	{
		$qb = $this->createQueryBuilder('user');
	
		$qb
		->leftJoin('user.groupes', 'gp')
		->addSelect('gp')
		->where($qb->expr()->in('gp.id', $userid));
		;
	
		return $qb
		->getQuery()
		->getResult()
		;
	}
}
