<?php

namespace SMARTASK\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function getRegisteredContactBuilder($userid)
	{
		 $qb = $this->createQueryBuilder('user'	)
		 ->leftJoin('user.contacts', 'contacts')
		 ->leftJoin('contacts.user', 'c_user');
		 
		 // A CORRIGER POUR N'AVOIR QUE LES CONTACT DE L'UTILISATEUR COURRANT
		/*
		$qb = $this->createQueryBuilder('user'	)
		->leftJoin('user.contacts', 'contacts')
		->leftJoin('contacts.user', 'c_user')
		->where('c_user.id= :userid')
		->setParameter('userid', $userid);
*/
		return $qb;
	}
	
	public function isUserBelongToGroup($gpId,$userid){
		$qb = $this->createQueryBuilder('user');
		
		// On fait une jointure avec l'entité Groupe avec pour alias « gp »
		$qb
		->innerJoin('user.groupes', 'gp')
		->addSelect('gp');
		
		// Puis on filtre sur le nom des catégories à l'aide d'un IN
		$qb->where($qb->expr()->in('gp.id', $gpId));
		$qb->where($qb->expr()->in('user.id', $userid));
		
		// Enfin, on retourne le résultat
		return $qb
		->getQuery()
		->getResult();
	}
}
