SMARTASK\APIBundle\Entity\Credentials:
    type: entity
    table: null
    repositoryClass: SMARTASK\APIBundle\Repository\CredentialsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        login:
            type: string
            length: 255
        password:
            type: string
            length: 255
    lifecycleCallbacks: {  }
