SMARTASK\APIBundle\Entity\AuthToken:
    exclusion_policy: none
    properties:
        id:
            groups: ['auth-token']
        value:
            groups: ['auth-token']
        createdAt:
            groups: ['auth-token']
        user_id:
            groups: ['auth-token']